# Generated by Django 5.0.3 on 2024-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=15)),
                ('lecID', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwordd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=90)),
                ('matric_no', models.CharField(max_length=10)),
                ('faculty', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=20)),
                ('level', models.IntegerField(default='heheh')),
                ('user_type', models.CharField(default='student', max_length=10)),
            ],
        ),
    ]
