# Generated by Django 5.0.3 on 2024-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='year',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturerID',
            field=models.CharField(default='BU1234', max_length=10, unique=True),
        ),
    ]
