# Generated by Django 5.0.4 on 2024-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_verified',
            new_name='is_courseRep',
        ),
        migrations.AddField(
            model_name='student',
            name='class_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
