# Generated by Django 5.0.3 on 2024-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_student_remove_lecturer_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecturerID',
            field=models.CharField(default='BU1234', max_length=10),
        ),
    ]
