# Generated by Django 5.0.3 on 2024-05-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_lecturer_lecturerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='lecturerID',
            new_name='lecID',
        ),
    ]
