# Generated by Django 5.0.3 on 2024-05-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_rename_lecturerid_lecturer_lecid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecID',
            field=models.CharField(max_length=10),
        ),
    ]
