# Generated by Django 5.0.3 on 2024-05-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_lecturer_lecid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='faculty',
        ),
    ]
