# Generated by Django 5.0.3 on 2024-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50)),
                ('departments', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
