# Generated by Django 5.0.3 on 2024-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dep_code', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50)),
                ('student_count_1', models.IntegerField(default=0)),
                ('student_count_2', models.IntegerField(default=0)),
                ('student_count_3', models.IntegerField(default=0)),
                ('student_count_4', models.IntegerField(default=0)),
                ('student_count_5', models.IntegerField(default=0)),
                ('faculty', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('departments', models.ManyToManyField(related_name='courses', to='course_list.department')),
            ],
        ),
    ]
