# Generated by Django 5.0.3 on 2024-05-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='clist',
            name='departments',
        ),
        migrations.AddField(
            model_name='clist',
            name='departments',
            field=models.ManyToManyField(to='course_list.department'),
        ),
    ]
