# Generated by Django 5.0.3 on 2024-06-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
