# Generated by Django 5.0.4 on 2024-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=200)),
                ('dep_code', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
    ]
