# Generated by Django 5.0.3 on 2024-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0004_alter_clist_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
    ]
