# Generated by Django 5.0.3 on 2024-05-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0005_alter_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_code',
            field=models.CharField(default='CSS', max_length=100),
        ),
    ]
