# Generated by Django 5.0.4 on 2024-05-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0006_department_dep_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(max_length=100),
        ),
    ]
