# Generated by Django 5.0.4 on 2024-07-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('announcement', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('code', models.ManyToManyField(related_name='announcements', to='courses.clist')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='announcements.announcements')),
            ],
        ),
    ]
