# Generated by Django 5.0.3 on 2024-07-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='signup.student'),
        ),
    ]
