# Generated by Django 5.0.3 on 2024-07-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='student',
        ),
    ]
